#!/usr/bin/env node

const esbuild = require("esbuild");

const buildJS = ({ src, dest }) => {
  try {
    esbuild.build({
      entryPoints: [src],
      outfile: dest,
      bundle: true,
      minify: true,
    });
  } catch {}
};

buildJS({
  src: "pkg/web/src/index.tsx",
  dest: "pkg/web/public/app.js",
});
